### ISSUE TITLE
economy_ko.py openpyxl

### ISSUE THREAD

**Issue by Tim232** [Shio7/Keter#2]
openpyxl쓰면 중간에 잠깐이라도 열면 에러나서 (아마 퍼미션 에러,,,??) 데이터베이스 다 날라갈 수 있는데 왜 openpyxl을 쓰는건가요...?? json이나 sql을 쓰는게 나을거같은데....

**Comment by Shio7** [comment]
아직 적당한 db가 없어서 그렇습니다. 나중에 웹도 같이 만들 때 바꿔볼게요

**Comment by redteadeveloper** [comment]
json 👍
